# Generated by Django 5.2.5 on 2025-10-11 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('personalidade', models.CharField(blank=True, max_length=10000, null=True)),
                ('ideais', models.CharField(blank=True, max_length=100, null=True)),
                ('vinculos', models.CharField(blank=True, max_length=1000, null=True)),
                ('fraquezas', models.CharField(blank=True, max_length=100, null=True)),
                ('talentos', models.CharField(blank=True, max_length=1000, null=True)),
                ('proficiencias_idiomas', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiencia', models.IntegerField(default='0')),
                ('inspiracao', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributo', to='ficha.base')),
            ],
        ),
        migrations.CreateModel(
            name='ataque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ataques', to='ficha.base')),
            ],
        ),
        migrations.CreateModel(
            name='ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='ficha.base')),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(blank=True, max_length=50, null=True)),
                ('antecedente', models.CharField(blank=True, max_length=50, null=True)),
                ('player', models.CharField(blank=True, max_length=50, null=True)),
                ('raca', models.CharField(blank=True, max_length=50, null=True)),
                ('alinhamento', models.CharField(blank=True, max_length=50, null=True)),
                ('xp', models.IntegerField(default='0')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='ficha.base')),
            ],
        ),
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.IntegerField(default='0')),
                ('pp', models.IntegerField(default='0')),
                ('pe', models.IntegerField(default='0')),
                ('po', models.IntegerField(default='0')),
                ('pl', models.IntegerField(default='0')),
                ('items', models.ManyToManyField(blank=True, to='base.item')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='ficha.base')),
            ],
        ),
    ]
