# Generated by Django 5.2.5 on 2025-09-03 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('personalidade', models.CharField(blank=True, max_length=10000, null=True)),
                ('ideais', models.CharField(blank=True, max_length=100, null=True)),
                ('vinculos', models.CharField(blank=True, max_length=1000, null=True)),
                ('fraquezas', models.CharField(blank=True, max_length=100, null=True)),
                ('talentos', models.CharField(blank=True, max_length=1000, null=True)),
                ('proficiencias_idiomas', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc', models.IntegerField(default='0')),
                ('pp', models.IntegerField(default='0')),
                ('pe', models.IntegerField(default='0')),
                ('po', models.IntegerField(default='0')),
                ('pl', models.IntegerField(default='0')),
                ('equipamentos', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='ficha.lore')),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(blank=True, max_length=50, null=True)),
                ('antecedente', models.CharField(blank=True, max_length=50, null=True)),
                ('player', models.CharField(blank=True, max_length=50, null=True)),
                ('raca', models.CharField(blank=True, max_length=50, null=True)),
                ('alinhamento', models.CharField(blank=True, max_length=50, null=True)),
                ('xp', models.IntegerField(default='0')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='ficha.lore')),
            ],
        ),
        migrations.CreateModel(
            name='atributos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiencia', models.IntegerField(default='0')),
                ('inspiracao', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='ficha.lore')),
            ],
        ),
        migrations.CreateModel(
            name='ataque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ataques', to='ficha.lore')),
            ],
        ),
    ]
