# Generated by Django 5.2.5 on 2025-09-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lore',
            new_name='base',
        ),
    ]
