# Generated by Django 5.2.5 on 2025-09-06 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('ficha', '0002_rename_lore_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='equipamentos',
        ),
        migrations.AddField(
            model_name='inventario',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='base.item'),
        ),
        migrations.CreateModel(
            name='atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiencia', models.IntegerField(default='0')),
                ('inspiracao', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributo', to='ficha.base')),
            ],
        ),
        migrations.DeleteModel(
            name='atributos',
        ),
    ]
