# Generated by Django 5.2.6 on 2025-09-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('ficha', '0003_remove_inventario_equipamentos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='equipamento',
        ),
        migrations.AddField(
            model_name='inventario',
            name='items',
            field=models.ManyToManyField(blank=True, to='base.item'),
        ),
    ]
