# Generated by Django 5.2.5 on 2025-09-30 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('ficha', '0004_remove_inventario_equipamento_inventario_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='ficha.base')),
            ],
        ),
    ]
