# Generated by Django 5.2.5 on 2025-09-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='alinhamento',
            field=models.CharField(default='sla', max_length=50, verbose_name='alinhamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='antecedente',
            field=models.CharField(default='sla', max_length=50, verbose_name='antecedente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='classe',
            field=models.CharField(default='sla', max_length=50, verbose_name='class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='equipamentos',
            field=models.CharField(default='sla', max_length=1000, verbose_name='equipamentos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='fraquezas',
            field=models.CharField(default='sla', max_length=100, verbose_name='fraquezas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='ideais',
            field=models.CharField(default='sla', max_length=100, verbose_name='ideais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='inspiracao',
            field=models.CharField(default='sla', max_length=100, verbose_name='foda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='pc',
            field=models.IntegerField(default='sla', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='pe',
            field=models.IntegerField(default='sla', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='personalidade',
            field=models.CharField(default='sla', max_length=10000, verbose_name='personalidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='pl',
            field=models.IntegerField(default='sla', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='player',
            field=models.CharField(default='sla', max_length=50, verbose_name='player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='po',
            field=models.IntegerField(default='sla', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='pp',
            field=models.IntegerField(default='sla', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='proficiencia',
            field=models.IntegerField(default='sla'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='proficiencias_idiomas',
            field=models.CharField(default='sla', max_length=1000, verbose_name='idioma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='raca',
            field=models.CharField(default='sla', max_length=50, verbose_name='raça'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='talentos',
            field=models.CharField(default='sla', max_length=1000, verbose_name='talentos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='vinculos',
            field=models.CharField(default='sla', max_length=1000, verbose_name='vinculos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='xp',
            field=models.IntegerField(default='sla'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ficha',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
